language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - libopencv3-dev

script:
  - chmod +x ./build.sh 
  - chmod +x ./install/dbow3.sh 
  - chmod +x ./install/opencv.sh
  - chmod +x ./install/boost.sh 
  - install/boost.sh
  - install/opencv.sh
  - install/dbow3.sh
  - ./build.sh
