language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - libopencv-dev

script: 
  - install/dbow3/install.sh
  - build.sh
